[package]
name = "openvpn-ldap"
version = "0.1.0"
authors = ["Patrick Kerrigan"]
edition = "2021"

[dependencies]
openvpn-plugin = "0.3.0"
openldap = "1.2.2"
libc = "*"
secrecy = "0.6.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
