name: Tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Install OpenLDAP
        run: sudo apt install -y libldap2-dev

      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Run tests
        run: cargo test --release
